-- RankEverything — Community list seed batch 3
-- Paste into Supabase → SQL Editor → Run

insert into public.lists (id, name, items, owner_id, owner_name, is_public, created_at) values

('lst_community_27', 'American fast food chains', ARRAY[
  'In-N-Out Burger',
  'Chick-fil-A',
  'Popeyes',
  'Five Guys',
  'Shake Shack',
  'Whataburger',
  'Raising Cane''s',
  'Culver''s',
  'Steak ''n Shake',
  'Jack in the Box',
  'McDonald''s',
  'Burger King',
  'Wendy''s',
  'Taco Bell',
  'Chipotle',
  'Subway',
  'Chili''s',
  'Applebee''s',
  'Denny''s',
  'IHOP',
  'Waffle House',
  'Panda Express',
  'Wingstop',
  'Buffalo Wild Wings',
  'Dairy Queen',
  'Sonic',
  'Arby''s',
  'Hardee''s',
  'Del Taco',
  'Zaxby''s'
], null, 'Community', true, now() - interval '2 hours'),

('lst_community_28', 'TTC subway stations', ARRAY[
  'Union',
  'Bloor-Yonge',
  'Spadina',
  'St. George',
  'Bay',
  'Museum',
  'Queen''s Park',
  'Osgoode',
  'St. Andrew',
  'King',
  'Queen',
  'Dundas',
  'College',
  'Wellesley',
  'Rosedale',
  'Summerhill',
  'St. Clair',
  'Davisville',
  'Eglinton',
  'Lawrence',
  'York Mills',
  'Sheppard-Yonge',
  'North York Centre',
  'Finch',
  'Kipling',
  'Islington',
  'Royal York',
  'Old Mill',
  'Jane',
  'Runnymede',
  'High Park',
  'Keele',
  'Dundas West',
  'Lansdowne',
  'Dufferin',
  'Ossington',
  'Christie',
  'Bathurst',
  'Broadview',
  'Chester',
  'Pape',
  'Donlands',
  'Greenwood',
  'Coxwell',
  'Woodbine',
  'Main Street',
  'Victoria Park',
  'Warden',
  'Kennedy'
], null, 'Community', true, now() - interval '1 hour'),

('lst_community_29', 'NYC MTA subway lines', ARRAY[
  '1 Train – Broadway Local',
  '2 Train – 7th Ave Express',
  '3 Train – 7th Ave Express',
  '4 Train – Lexington Ave Express',
  '5 Train – Lexington Ave Express',
  '6 Train – Lexington Ave Local',
  '7 Train – Flushing',
  'A Train – 8th Ave Express',
  'C Train – 8th Ave Local',
  'E Train – Queens',
  'B Train – 6th Ave Express',
  'D Train – 6th Ave Express',
  'F Train – 6th Ave Local',
  'M Train – 6th Ave/Queens Blvd',
  'G Train – Crosstown',
  'J Train – Nassau St',
  'Z Train – Nassau St Express',
  'L Train – 14th St/Canarsie',
  'N Train – Broadway Express',
  'Q Train – 2nd Ave/Broadway',
  'R Train – Broadway Local',
  'W Train – Astoria',
  'S Train – 42nd St Shuttle'
], null, 'Community', true, now() - interval '45 minutes'),

('lst_community_30', 'What should we eat tonight?', ARRAY[
  'Sushi',
  'Burgers',
  'Pizza',
  'Tacos',
  'Thai',
  'Indian curry',
  'Chinese takeout',
  'Korean BBQ',
  'Ramen',
  'Mediterranean',
  'Italian pasta',
  'Fried chicken',
  'Poke bowl',
  'Burritos',
  'Dim sum',
  'Vietnamese pho',
  'Greek',
  'Sandwiches/deli',
  'BBQ ribs',
  'Seafood',
  'Ethiopian',
  'Peruvian',
  'Salads',
  'Just cook at home'
], null, 'Community', true, now() - interval '30 minutes'),

('lst_community_31', 'Grain bowl chains', ARRAY[
  'Cava',
  'Chipotle',
  'Naya',
  'Sweetgreen',
  'Dig',
  'INDAY',
  'Pokéworks',
  'Tender Loving Empire',
  'Falafel Inc.',
  'Tender Greens',
  'Eataly grain bowls',
  'Cafe Joyeux',
  'Just Salad',
  'Chop''t',
  'Flower Child',
  'Mixt',
  'Lemonade',
  'Souvla',
  'Sajj Mediterranean',
  'Noon Mediterranean'
], null, 'Community', true, now() - interval '15 minutes')

on conflict (id) do update set items = excluded.items, name = excluded.name;
